In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df_orig = pd.read_csv('vehicles_dataset.csv')

## Пропуски

In [27]:
df_nodub = df_orig.drop_duplicates()
df_nodub.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 10049
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              10000 non-null  int64
 1   url             10000 non-null  object
 2   region          10000 non-null  object
 3   region_url      10000 non-null  object
 4   price           10000 non-null  int64
 5   year            9964 non-null   float64
 6   manufacturer    9618 non-null   object
 7   model           9872 non-null   object
 8   condition       6234 non-null   object
 9   cylinders       5920 non-null   object
 10  fuel            9937 non-null   object
 11  odometer        9957 non-null   float64
 12  title_status    9834 non-null   object
 13  transmission    9955 non-null   object
 14  VIN             6062 non-null   object
 15  drive           6994 non-null   object
 16  size            2809 non-null   object
 17  type            7806 non-null   object
 18  paint_color     7050 non-null   object
 19  image_url       9998 non-null   object
 20  description     9998 non-null   object
 21  county          0 non-null      float64
 22  state           10000 non-null  object
 23  lat             9902 non-null   float64
 24  long            9902 non-null   float64
 25  posting_date    9998 non-null   object
 26  price_category  10000 non-null  object
dtypes: float64(5), int64(2), object(20)
memory usage: 2.1+ MB

In [28]:
(df_nodub.isna().sum() / len(df_nodub) * 100).sort_values()

id                  0.00
state               0.00
price               0.00
price_category      0.00
region              0.00
url                 0.00
region_url          0.00
description         0.02
image_url           0.02
posting_date        0.02
year                0.36
odometer            0.43
transmission        0.45
fuel                0.63
lat                 0.98
long                0.98
model               1.28
title_status        1.66
manufacturer        3.82
type               21.94
paint_color        29.50
drive              30.06
condition          37.66
VIN                39.38
cylinders          40.80
size               71.91
county            100.00
dtype: float64

## обработка года выпуска авто

In [29]:
print(df_nodub.year.median())
print(df_nodub.year.mean())
print("\n")
print(df_nodub.year.isna().sum())

df_nodub.year = df_nodub.year.fillna(df_nodub.year.mean())
df_nodub.transmission = df_nodub.transmission.fillna("automatic")

df_nodub.year.info()

2013.0
2010.92794058611


36
<class 'pandas.core.series.Series'>
Index: 10000 entries, 0 to 10049
Series name: year
Non-Null Count  Dtype
--------------  -----
10000 non-null  float64
dtypes: float64(1)
memory usage: 156.2 KB

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15996\2943979847.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nodub.year = df_nodub.year.fillna(df_nodub.year.mean())
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15996\2943979847.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nodub.transmission = df_nodub.transmission.fillna("automatic")

In [30]:
print(df_nodub.year.mean())

2010.9279405861103

видно, что после заполнения средней величиной общее среднее изменилось незначительно

## обработка типа топлива

In [31]:
uniqfuel = df_nodub.fuel.unique().tolist()
uniqfuel

['diesel', nan, 'gas', 'other', 'electric', 'hybrid']

In [32]:
uniqfuel = [fuel for fuel in uniqfuel if isinstance(fuel, str)]
uniqfuel

['diesel', 'gas', 'other', 'electric', 'hybrid']

In [33]:
for f in uniqfuel:
    print(f"{f} - {len(df_nodub[df_nodub.fuel == f])}")

len(df_nodub.fuel[df_nodub.fuel == "gas"]) / 10000

diesel - 653
gas - 8402
other - 730
electric - 44
hybrid - 108

0.8402

In [34]:
df_nodub.fuel = df_nodub.fuel.fillna("gas")
len(df_nodub.fuel[df_nodub.fuel == "gas"]) / 10000

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15996\4139182292.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nodub.fuel = df_nodub.fuel.fillna("gas")

0.8465

## Модель авто

In [35]:
uniqmodel = df_nodub.model.unique().tolist()
uniqmodel, len(uniqmodel)

(['2500 crew cab big horn',
  'explorer 4wd 4dr xlt',
  'golf r hatchback',
  'rav4',
  'altima',
  '1 series 128i coupe 2d',
  'fusion se',
  'accord',
  'charger',
  'galant',
  '500 pop',
  'town car',
  'e-series van universal by glaval designer luxury series conversion leather 16" dvd limo lighting bed',
  'g. caravan se',
  'silverado 2500hd 4x4',
  'mustang',
  'maxima sv',
  'civic',
  'explorer',
  'vue v6',
  'oldsmobile 442',
  'tahoe',
  'f-350',
  'f150',
  'clubman',
  'xts sedan 4d',
  '3500',
  '2500 4x4',
  'rogue',
  'silverado 1500',
  'compass 4x4',
  'camry solara 2dr cpe se v6 auto (natl)',
  'f450 deisel power stroke',
  'silverado',
  'renegade',
  'forte5',
  'f-150',
  'wrangler unlimited all new',
  'mazda3 touring sedan 4d',
  '535i',
  'park avenue',
  'focus',
  'camry',
  'gx',
  'f150 lariat',
  'titan',
  'corolla',
  'colorado extended cab',
  'tiguan 2.0t s',
  'impreza',
  'coe',
  'jetta s',
  'super duty f-250 srw',
  'altima 2.5 s',
  'q5',
  'es 350 f sport sedan 4d',
  'lx450',
  'pilot',
  'Diahatsu',
  nan,
  'sequoia',
  '1500 classic',
  'tucson se awd',
  'sierra 1500',
  'mazda3',
  'grand cherokee laredo sport',
  'nautilus reserve sport',
  'f-150 4wd supercrew 145" platinum',
  'elantra',
  'x1',
  'fusion',
  'camaro',
  'accord sedan sport 1.5t',
  'benz s500',
  'tacoma double cab',
  'tsx sedan 4d',
  'sebring',
  'yukon denali sport utility',
  'cooper s',
  'enclave premium sport',
  'x4',
  'sequioa',
  'wrangler',
  'xts',
  'xc90',
  'is300 rwd gas sedan auto',
  'f350 super duty',
  'romeo stelvio ti sport',
  'ranger sport extended cab',
  'spark',
  'enclave',
  '7 series 750li xdrive sedan',
  'express 3500 lt',
  'q7',
  'es',
  'corolla le',
  'tribute',
  'xv crosstrek',
  'impala',
  '5 series',
  'c300 c-300 luxury awd',
  'frontier crew cab',
  'titan xd single cab sv',
  'f-150 xlt 4x4',
  '7 series',
  'fit fwd gas hatchback',
  'cc 3.6 vr6 4motion',
  'transit 350',
  'outback 2.5i wagon',
  '1500',
  'q5 premium sport utility 4d',
  'benz',
  'silverado lt crew cab 4x4',
  '2500',
  'passat',
  '350z',
  'focus titanium sedan 4d',
  'optima',
  'camry xse',
  'f550 xl',
  'c10 short box',
  'expedition el',
  'pathfinder',
  'pilot touring sport',
  'challenger',
  '200',
  'taurus',
  'evoque',
  '500 abarth hatchback 2d',
  'x3 xdrive28i sport utility',
  'mazda3 i sv sedan 4d',
  'arcadia 4x4',
  'cr-v',
  'xt6',
  'jetta sportwagen',
  'sante fe',
  'cc',
  '3500 slt',
  'rogue select s sport',
  'c10',
  'versa s',
  'e150 econoline',
  'lifted silverado 3500',
  'equinox lt',
  'explorer xlt',
  'yukon xl',
  'sonata se sedan 4d',
  'soul',
  'corolla s',
  'regal turbo',
  'Scion iM Hatchback 4D',
  'lucerne',
  'rav4 hybrid limited sport',
  'super duty f-350 srw',
  'f250 super duty',
  '1500 tradesman quad cab',
  'odyssey',
  's60 t5 premier sedan 4d',
  'yukon slt',
  'transit 250',
  'cruze lt turbo',
  'mkx',
  'sienna',
  '914',
  'transit connect cargo xlt 4',
  'equinox',
  '300c v6',
  'crosstrek',
  'Voltswagon Beetle',
  'sonata se',
  'a6',
  'sierra 1500 double cab slt',
  '550i',
  'sport',
  'town and country',
  'mazda6',
  'challenger srt 392 rwd gas',
  'sorento lx',
  'malibu ls - one owner',
  'wrangler cj5',
  'colorado',
  'THOMAS SCHOOL BUS',
  'c-class',
  'super beetle',
  '500 sport ruby',
  'f-150 xlt',
  'patriot',
  'fj cruiser',
  'trailblazer lt w/1lt',
  'c-max hybrid se wagon 4d',
  '370z nismo coupe 2d',
  'mx-5 miata',
  'malibu',
  'sl-class sl 550',
  'e250 extended',
  'mx-5 miata grand touring',
  'benz e500',
  'f-250',
  'cc4500',
  '328i',
  'm class',
  'nx',
  'escape',
  'Emergency One Fire Truck',
  'sienna xle',
  'corvette grand sport',
  'liberty suv',
  'vibe gt',
  'mustang gt coupe 2d',
  'edge',
  'sonata',
  'model s sedan 4d',
  'chysler 300',
  'express passenger',
  'tacoma',
  's5 premium plus sedan 4d',
  'legacy',
  'transit 150 cargo van',
  '1500 lone star',
  'accord lx',
  'wrangler unlimited sahara',
  'v6',
  'tucson',
  'dts',
  'silverado diesels 2500',
  'frontier crew cab 4x2 sv auto',
  'f350 super duty crew cab',
  '200 limited',
  'navigator',
  'f-150 lariat crew cab 4x4',
  'crv ex awd',
  'rdx',
  'wrangler unlimited rubicon',
  'tiguan limited 2.0t',
  'avalanche 1500',
  's10 pickup',
  'silverado 2500hd',
  '488 gtb',
  'rdx sh-awd a-spec pkg',
  'panamera',
  'Genesis G70 2.0T Sedan 4D',
  'suzuki verona',
  'neon',
  'cougar',
  's5 prestige coupe 2d',
  'stinger premium',
  'boxster s',
  'tiguan',
  'suburban 1500',
  'forte koup ex coupe 2d',
  'suburban',
  'grand cherokee',
  'verano',
  'camaro lt coupe 2d',
  'passat 2.0t wolfsburg',
  'prius prime',
  'ridgeline sport pickup 4d',
  'silverado 1500 ld',
  'promaster 2500 cargo van',
  'odyssey touring',
  'sierra 2500 hd',
  '5 series 540i xdrive sedan',
  'SPECIAL FINANCE PROGRAM 2020',
  'sorento 2wdv6 sx',
  'optima lx',
  'xt4 sport suv 4d',
  'wrx sti limited awd',
  'golf gti s hatchback',
  'mkz select sedan 4d',
  'tiguan sel premium',
  'cts-v coupe',
  '1500 sport 4x4 1/2 ton',
  '500',
  'traverse lt',
  'journey',
  'caprice classic',
  'f250 super duty lariat',
  'rx 350',
  'traverse premier',
  'avenger mainstreet heat',
  '2002 f 450',
  'f150 xlt 4wd f-150 4x4',
  'corvette',
  'limousine',
  'eurovan',
  'mustang cobra svt',
  'rav4 xle',
  'srx',
  'caravan',
  'c70 convertible',
  'cherokee',
  'town & country',
  'mkz hybrid sedan 4d',
  'rivera',
  'tl',
  'CATERPILLAR CT660S',
  'crosstrek premium cvt awd',
  '3.2 tl',
  'ranger',
  'sentra',
  'f150 supercrew cab xlt',
  'silverado 1500 lt crew',
  'g37 sedan',
  'charger sxt sedan 4d',
  'model t',
  'k10',
  'mdx',
  'rx8',
  'cayenne 4dr s hybrid',
  'x5 xdrive35i awd',
  '3 series 340i sedan 4d',
  'tundra',
  'silverado 1500 lt',
  '5 series 528i sedan 4d',
  'forte5 lx',
  'highlander',
  'rx 300',
  'sierra',
  'Super Duty F-350 SRW',
  '1500 slt',
  '3 series',
  'santa fe',
  'Grand Caravan',
  'tacoma limited 4x4',
  'pilot ex-l',
  'prius',
  'maxima 3.5 sl',
  'yaris sedan',
  'econoline commercial cutaway',
  'qx50 sport utility 4d',
  'aura',
  'impala lt',
  '2500 laramie 4dr megacab',
  'outlander sport es',
  'dakota',
  'f250',
  'isuzu pickup',
  'fusion platinum sedan 4d',
  'discovery',
  'eos',
  'pickup 1500',
  'grand cherokee laredo 4wd',
  'gti autobahn',
  'titan xd crew cab sv',
  'sierra 1500 sle/z71 monster',
  'cadenza',
  'genesis coupe 3.8 2d',
  'a5 cabriolet',
  'isuzu npr',
  'patriot sport',
  'outback 3.0 r h6 ll bean',
  'escape sel',
  'Chevey uplander',
  'f-250 sd',
  '6',
  'silverado 1500 ext cab 143.5" wb 4wd ls',
  'qx60 3.5 sport utility',
  'flex se',
  's5 premium plus convertible',
  'sierra all terrrain edition',
  'mariner',
  'durango r/t',
  'sierra 2500hd',
  'macan s sport utility 4d',
  'Genesis G70 3.3T Advanced Sedan',
  'silverado 1500 ls 4x4',
  'f150 xlt supercrew',
  '500 sport 2dr hatchback',
  'cx-9 touring awd',
  'yukon slt 4x4',
  'armada',
  'lacrosse',
  'Hot Rod',
  'Champion Shuttle Bus',
  'lacrosse cx',
  'x5',
  'transit cargo',
  'a4',
  'sierra 2500 hd double cab',
  'f450',
  'gt-r',
  'cvr',
  'santa fe 2.0t sel sport',
  'camaro z28',
  'sierra 1500 crew cab slt',
  'escape se awd',
  'jetta',
  'land cruiser',
  'envision',
  'camry se automatic',
  'Scion tC',
  'g6',
  'model s signature',
  '750xi xdrive m-sport edition',
  'ranger supercrew xlt pickup',
  'silverado 1500 lt ext cab lifted',
  'solara',
  'f700',
  'cooper',
  'corolla le 4dr sedan',
  'cruze',
  'eqinox',
  'g4500',
  'continental sedan 4d',
  'outback',
  'escape xlt 4x4',
  'cx-5 grand touring sport',
  'eclipse',
  'HINO 268A',
  'benz e320',
  'envoy denali',
  '2021 spark',
  'f150 supercrew cab',
  'cougar xr7',
  'regal',
  'e-class',
  'mazda2 sport',
  'tundra crewmax sr5 pickup',
  'q60 3.0t premium coupe',
  'qx60',
  'mazda3 touring hatchback',
  'camry hybrid',
  'venza xle awd',
  'express cargo van',
  'trax',
  'silverado 1500 double',
  'malibu lt',
  'grand cherokee limited',
  'ss sedan 4d',
  'f550',
  'f-pace',
  'terrain',
  'mdx sh-awd sport utility',
  'avalanche z71',
  'quest sv',
  'tacoma access cab trd',
  'dump truck',
  'fiesta',
  'ats luxury sedan 4d',
  'wrangler unlimited sahara, $374.52, $1500 down, 2.9% apr, $374.52, $1500 down, 2.9% apr,',
  'rx7',
  'scion tc',
  'xc90 momentum',
  'sierra 1500 4x4 1/2 ton gas',
  'q5 3.0t premium plus sport',
  '2018',
  'envoy 4x4',
  'elantra gt',
  'e350 passenger van',
  'f350',
  'hyndai elantra',
  'wrangler sport suv 2d',
  'silverado 2500',
  'tacoma prerunner v6',
  'suburban ltz',
  'e-series cargo',
  'avalon hybrid limited',
  'brz limited',
  '1954 Packard Patrician Limousine',
  'ats',
  'accent se sedan 4d',
  'acadia denali',
  'civic ex',
  '4runner',
  'enclave premium group',
  '3',
  'accord cpe ex',
  'all vehicles',
  'charger glhs',
  'tundra sr5 4wd 5.7l 1 owner',
  'c-class c 300',
  'xt5 luxury sport',
  'tacoma trd',
  'tacoma 4x4',
  'f-250 super duty lariat 4x4',
  'a3 tdi premium sedan 4d',
  '4runner sr5 sport utility',
  'f150 platinum',
  'v60 cross country t5',
  '4500',
  'accord ex-l',
  'frontier',
  'tsx 2.4',
  'golf r 4motion',
  'Genesis G80 3.8 Sedan 4D',
  'titan xd',
  'wrangler unlimited',
  '500l',
  'outlander gt',
  'xc90 t6 r design awd gas',
  'olet Silverado 1500',
  'bronco xlt',
  'Plymouth Barracuda',
  'f-250 super duty',
  'Maserati Quattroporte',
  'model 3',
  'expedition limited',
  'tlx 3.5 sedan 4d',
  'camry le automatic',
  'wrangler sport s utility 2d',
  'silverado 2500 hd',
  'f250 super duty 4x4',
  'versa',
  'trax lt sport utility',
  'camry se',
  'corolla camry',
  'tsx',
  'golf',
  'f-150 4x4 step side',
  'sts',
  'enclave leather sport',
  '300zx 2+2',
  '86 trd special edition',
  'ranger xlt fx4 4x4 1/4 ton',
  '300',
  '4 series 430i xdrive',
  'model a',
  'x3 xdrive30i sport utility',
  'grand caravan sxt',
  'transit connect passenger',
  'cj5',
  'grand caravan',
  'eldorado biarritz',
  'cr-v lx automatic',
  'cj8 scrambler',
  'econoline e350',
  'crosstrek premium',
  'f-250sd',
  'Hummer H2',
  'qx50',
  '911 carrera',
  'hhr ls_panel 4dr wagon',
  'outlander sport',
  'g g37 sport coupe 2d',
  'cx-9',
  'outlander phev sel',
  'jetta sedan',
  'lx 570',
  'sentra sv automatic',
  'benz c300',
  'city express',
  'sonata hybrid',
  'commander',
  'discovery sport se',
  'e46 m3',
  'grand marquis',
  'mercedes-amg',
  'ram1500',
  'f-150 platinum crew ecoboost 3.5l',
  'sable',
  'f150 supercrew cab xl',
  'soul ! wagon 4d',
  'sienna xle awd',
  'traverse',
  'sonoma',
  'mustang gt premium 2dr conv',
  'certified',
  'x5 xdrive30i',
  'sedona',
  'deville',
  'genesis coupe',
  'sonic',
  'civic si sedan 4d',
  'mazda3 i touring hatchback',
  'outback awd 3.6r touring',
  'five hundred sel',
  'dart',
  '1999 International',
  '1500 big horn/lone star',
  'seirra',
  'cooper hardtop',
  'cobalt lt',
  'e-250',
  'f150 xlt 4wd',
  'camaro ss convertible',
  'm3 coupe 2d',
  'avalanche',
  'thunderbird deluxe',
  'super duty f-450 drw',
  'rdx sport utility 4d',
  'model 3 standard range',
  'sorento',
  'transit cargo cargo 250',
  'hardtop cooper s hatchback',
  '5 series 535d xdrive sedan',
  's60 t6 r-design sedan 4d',
  'tacoma double cab pickup',
  'GRAND CARAVAN SXT, 3.6L V6',
  'c 250 sport',
  'f-150 platinum 4x4',
  'pickup',
  'expedition xlt',
  'impala ss',
  'blue bird',
  'veloster n coupe 3d',
  'm-class',
  'e-pace p300 r-dynamic s',
  'a6 45 tfsi premium plus',
  'F-150',
  'qx80',
  'encore preferred sport',
  'grand cherokee laredo',
  'gti hatchback sedan',
  'cts 3.6 premium',
  'Odyssey',
  '300 300s sedan 4d',
  'envoy',
  'cts',
  'truck 3500 quad cab',
  's90 t6 momentum sedan 4d',
  'mkx awd',
  '240 dl',
  'focus titanium hatchback 4d',
  'a5 premium plus sedan 4d',
  'silverado 3500',
  'cooper s 2 door cooper s',
  'srx awd',
  'Maserati Ghibli',
  'nv200 sv cargo van',
  'prius c',
  'pt cruiser',
  'focus se',
  'prius v',
  'forester',
  'Cemetery Plot',
  'tsx tech pkg',
  'liberty',
  '3500 limited',
  'f-350 lariat ultimate lifted diesel only 49k mles loaded',
  'windstar limited',
  'sonata sel sedan 4d',
  'terrain sle sport utility 4d',
  'f150 super cab xlt pickup',
  'miata',
  'taurus se',
  'ats 2.0l turbo standard',
  'model s',
  's320',
  'mkx reserve sport',
  '5 series 535i sedan 4d',
  'FORD* FIESTA*',
  'mdx advance pkg sport',
  'focus st hatchback 4d',
  'bel air/150/210',
  'colorado crew cab z71',
  '4 series 430i convertible 2d',
  'silverado 1500 regular',
  'rainier',
  'sienna l minivan 4d',
  'civic sedan',
  'escalade',
  'a6 2.0t premium plus sedan',
  'mx-5 miata club',
  'benz ml350 4matic',
  'i-miev',
  'hse 4x4 s',
  'e-pace p250 se sport',
  's-10 ext cab 123" wb ls',
  'tacoma trd off-road full ads coil over adjustable resivoirs kit* koning ultra light 17"wheels*bfg ko2 tires*trd off road*camburg upper control arms*trd pro grill & roof rack*nav*tech pkg*',
  'fj cruiser 4x4',
  'q8 premium sport utility 4d',
  '4runner sr5',
  'wrangler sahara',
  'mazda3 touring 2.5',
  'e-pace p250 s sport',
  'silverado 3500hd',
  'sienna xle 7 passenger',
  'renegade sport suv 4d',
  'ion',
  'yukon',
  'ranger xlt',
  'accent',
  'durango',
  'elantra se',
  'sedona lx',
  'camaro ss 2ss/rs',
  'avalon xls',
  'deluxe',
  'vibe base',
  'lx 470',
  'eos komfort',
  'expedition max',
  '328i gt',
  'international dump truck',
  'ls 460 sedan 4d',
  'aveo',
  'challenger sxt rwd gas',
  '535xi',
  'cooper clubman s',
  'ranger supercab xl pickup',
  'escape se',
  'civic ex sedan',
  'focus st hatchback',
  'es 350 sedan 4d',
  'tundra double cab sr',
  'cooper countryman',
  'civic lx',
  'forte koup',
  'murano sl',
  'pick up',
  'colorado crew cab work',
  'fiesta se',
  'encore gx select sport',
  'x1 xdrive28i',
  'm-class ml 350',
  'enclave essence sport',
  'sierra 2500hd available wifi',
  'sienna se minivan 4d',
  'legacy 2.5i special ed',
  'rl',
  'gto',
  'camry hybrid xle sedan 4d',
  'nv2500 hd cargo',
  'clk-class',
  'ct5 premium luxury',
  'enclave cxl',
  'silverado 2500 high country lifted diesel 4x4 loaded',
  'colorado lt',
  'verano base',
  'tundra 4wd',
  '3-series',
  'sierra 1500 sleextended',
  'impreza 2.5i premium',
  'Isuzu NPR HD GAS REG',
  'b2200',
  'a6 2.0t premium sedan 4d',
  'f-150 truck 4x4',
  'camaro ls',
  '4 series 440i xdrive gran',
  '3i touring',
  'xe 20d sedan 4d',
  'e-class e 300',
  'qx60 luxe sport utility',
  'c 300',
  'caliber',
  '323i',
  'rsx coupe 2.0l automatic leather moon sport wheels',
  '545i',
  'frontier crew cab s',
  's60',
  '5 series 530e iperformance',
  'pacifica touring l fwd',
  'tacoma access cab sr5',
  'jeepster commando',
  '1500 crew cab big horn',
  'tahoe z71 4x4',
  'es 330',
  'svx',
  'caliber sxt',
  'captiva sport ls',
  'tucson sport',
  'expedition eddie bauer',
  'quest sl',
  'forte',
  'f 450 super duty',
  'compass',
  '2500 slt',
  's8',
  '300c hemi',
  'charger gt sedan 4d',
  'pathfinder le',
  '1500 crew cab tradesman',
  'wrangler unlimited sport',
  'ls 430',
  'f-450sd',
  'sprinter cargo vans',
  'acadia',
  'solara se',
  'tundra 4x4',
  'expedition',
  'econoline',
  'plymouth scamp',
  'suburban lt',
  'CR-V',
  'silverado 1500 work tr',
  'camry le',
  'odyssey exl',
  'xterra',
  'fit',
  'f-250 super duty xlt',
  'international prostar',
  'silverado 1500 crew',
  'f150 super cab lariat',
  'impala ls',
  'scion iq',
  '2500 longhorn mega 4x4',
  'qx80 sport utility 4d',
  'f650',
  'expedition el king ranch',
  'explorer limited automatic',
  'quest',
  'trax ls',
  'nx 300h sport utility 4d',
  'trailblazer ls 4x4',
  'lifted f150 fx4 4x4 1/2 ton',
  'cobalt',
  'jetta 1.4t s sedan 4d',
  '2500 quad cab',
  'sierra 2500',
  'pathfinder le 4wd',
  'Lotus Diva Roadster',
  'transit connect xlt',
  'encore preferred',
  'mkz sedan 4d',
  'rav4 limited i4 2wd 4-speed automatic',
  'murano',
  'f550 4x4 crew cab',
  'IC IC',
  'silverado 1500 ltz 4x4',
  '1500 crew cab express pickup',
  'santa fe gls',
  'mdx touring w/navi w/res',
  's7 4.0 tfsi prestige',
  'f350 crew cab',
  'Sea Ray Sea Ray',
  'civic si',
  'tundra 1794 edition',
  'SCION XB',
  'atlas',
  'srx~awesome colors~ navigation~ camera~ factory ch',
  'civic lx sedan 4d',
  'atlas sel 4motion',
  'outlander',
  'benz e350',
  'c-7500 multiple uses perfect',
  'a Sienna',
  'encore',
  '6 series',
  'lesabre',
  'sierra 1500 extended cab slt',
  'eclipse cross es',
  'civic hybrid',
  'aveo ls',
  'f150 supercrew cab fx4',
  'es 350',
  'tacoma prerunner',
  'INTERNATIONAL WORKSTAR 7400',
  'traverse ls sport',
  'acadia sle',
  'enclave leather',
  'challenger gt coupe 2d',
  'versa note',
  'International TerraStar',
  'q5 premium plus sport',
  'hse',
  'grand caravan se',
  'camry hybrid le',
  'countryman',
  'thunderbird',
  'durango gt sport utility',
  'e350 bucket van',
  '1500 quad cab laramie pickup',
  'quattro tt',
  'kicks',
  'juke nismo',
  'impreza wrx sti',
  'savana',
  's2000',
  'cherokee trailhawk 4x4 gas',
  'fj 62',
  'a6 3.0t prestige sedan 4d',
  'benz sl 320',
  'beetle 1.8t fleet',
  'gladiator',
  'ilx premium',
  'brz limited coupe 2d',
  'willys',
  'scion frs',
  'titan sv',
  'acadia slt',
  'sentra s',
  'hhr',
  'new beetle',
  'escape s',
  'mkz reserve sedan 4d',
  'renegade trailhawk sport',
  'sequoia sr5 platinum',
  'sierra 1500 sle',
  'transit van',
  'wrangler sport',
  'malibu ltz',
  'e350 super duty',
  'g35x',
  'q70',
  'savana 12 passenger',
  'santa fe sport awd',
  'equinox lt awd',
  'eurovan camper',
  '1978 LincolnTown Cars',
  'international 9400i',
  'romeo stelvio',
  'cooper clubman',
  'prius hybrid',
  'c-hr',
  'e-series cargo van',
  'srx4',
  'santa fe gls 4dr suv',
  'mpv',
  'ranger xl 4x2',
  '370z coupe',
  'Flexible Down Payments',
  'cc sport',
  'silverado 2500hd ltz',
  'camry hybrid le sedan 4d',
  'bonanza',
  'enclave avenir sport',
  'mazda3 i sport',
  'gle 400 4matic',
  'sienna xle limited handic',
  'malibu lt sedan 4d',
  'silverado 1500 4x2 re',
  'g37',
  'corvette coupe',
  'sentra sv sedan 4d',
  'c8500',
  'expedition xlt sport',
  'f150 regular cab xl pickup',
  'sierra 1500 regular cab',
  'focus electric hatchback 4d',
  'maxima',
  'a4 quattro',
  'cr-v lx sport utility 4d',
  'cx9',
  'titan pro-4x',
  'is 250 sedan 4d',
  'sl-class',
  'a5 premium sedan 4d',
  'grand caravan passenger se',
  'utility truck',
  'is 250',
  'freestyle awd',
  'camaro ls rwd gas',
  '300-series',
  'magnum',
  'blazer 2lt sport',
  'a4 2.0t quattro',
  'tlx',
  '1500 quad cab slt pickup 4d',
  'x5 xdrive35d',
  '325i',
  'hummer h3 4dr 4wd suv',
  'benz c250 coupe',
  'wrangler sport unlimited',
  'f-350 super duty',
  'k10 4x4',
  'g37s',
  'tiguan sel',
  'prius four panel solar',
  '280zx',
  'romeo giulia ti sedan 4d',
  'q50 3.0t luxe sedan 4d',
  'spark lt',
  'cruze lt',
  'excursion',
  'mountaineer',
  'rx',
  'charger scat pack sedan 4d',
  '2007 Silverado crew cab 4x4',
  'Janesville',
  'sierra 1500 double cab',
  'focus ses',
  'cruze 1lt auto',
  'gls new beetle convertible',
  'sierra 1500 elevation',
  'xk8',
  'ranger supercrew xl pickup',
  'ls 400',
  'forte ex hatchback',
  'forester xt premium',
  'navigator sport utility',
  'f-450 super duty',
  'e350',
  'sportage lx sport utility 4d',
  'xj',
  'f150 4x4',
  'transit',
  'liberty limited',
  'FORD/RANGER',
  'freightliner m2',
  'e-pace p300 r-dynamic se',
  'camry xle',
  'rav4 limited',
  'grand caravan se wheelcha',
  'uplander cargo van',
  'promaster cargo van 1500 low roof 118" wb',
  'f250 super duty crew cab',
  'sierra 1500 double cab sle',
  'tacoma access cab pickup',
  '5500',
  'sienna limited awd',
  'legacy 2.5i sedan 4d',
  'cadvwrambuick',
  'pacifica',
  'passport sport suv 4d',
  'patriot high altitude 4x4',
  'durango sxt',

In [36]:
#minidf = df_nodub[df_nodub.model.isna()]

# sizes = [len(df_nodub[df_nodub.model == m]) for m in uniqmodel]

# max(sizes)

In [37]:
df_nodub = df_nodub.dropna(subset=["model"])
df_nodub

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,type,paint_color,image_url,description,county,state,lat,long,posting_date,price_category
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020.0,ram,2500 crew cab big horn,good,NaN,...,pickup,silver,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,NaN,tn,35.060000,-85.250000,2021-04-17T12:30:50-0400,high
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016.0,ford,explorer 4wd 4dr xlt,NaN,6 cylinders,...,SUV,black,https://images.craigslist.org/00x0x_26jl9F0cnL...,***Call Us for more information at: 201-635-14...,NaN,nj,40.821805,-74.061962,2021-05-03T15:40:21-0400,medium
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017.0,volkswagen,golf r hatchback,good,NaN,...,sedan,NaN,https://images.craigslist.org/00y0y_eeZjWeiSfb...,Carvana is the safer way to buy a car During t...,NaN,ca,33.779214,-84.411811,2021-04-28T03:52:20-0700,high
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013.0,toyota,rav4,NaN,NaN,...,wagon,white,https://images.craigslist.org/00606_iGe5iXidib...,2013 Toyota RAV4 XLE 4dr SUV Offered by: R...,NaN,nc,35.715954,-78.655304,2021-04-17T10:08:57-0400,medium
4,7316474668,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800,2021.0,nissan,altima,new,4 cylinders,...,NaN,NaN,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,2021 Nissan Altima Sv with Only 8 K Miles Titl...,NaN,ny,40.654800,-73.609700,2021-05-03T18:32:06-0400,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10045,7304876387,https://chautauqua.craigslist.org/ctd/d/falcon...,chautauqua,https://chautauqua.craigslist.org,4495,2002.0,toyota,rav4,good,4 cylinders,...,SUV,white,https://images.craigslist.org/00n0n_aaEBqmzz5Z...,Transmission:Automatic Exterior Color:WHITE In...,NaN,ny,42.123900,-79.189500,2021-04-10T16:33:57-0400,low
10046,7316152972,https://binghamton.craigslist.org/ctd/d/roches...,binghamton,https://binghamton.craigslist.org,14495,2008.0,jeep,wrangler,good,6 cylinders,...,SUV,grey,https://images.craigslist.org/00000_9ZNVdXaiei...,2008 Jeep Wrangler X Offered by: R&L Auto -- ...,NaN,ny,43.216990,-77.755610,2021-05-03T09:36:30-0400,medium
10047,7310993818,https://salem.craigslist.org/ctd/d/salem-2011-...,salem,https://salem.craigslist.org,8995,2011.0,audi,a3 2.0t premium plus pzev,NaN,4 cylinders,...,wagon,black,https://images.craigslist.org/00X0X_k5JiZDDyqM...,2011 Audi A3 2.0T Premium Plus PZEV Wagon2011 ...,NaN,or,44.925908,-122.982753,2021-04-22T12:14:01-0700,low
10048,7306637427,https://madison.craigslist.org/ctd/d/madison-2...,madison,https://madison.craigslist.org,31900,2015.0,porsche,cayenne,good,6 cylinders,...,wagon,brown,https://images.craigslist.org/00O0O_gBihGEQxYT...,"2015 Porsche Cayenne AWD 4dr S E-Hybrid - $31,...",NaN,wi,43.029559,-89.397796,2021-04-14T09:14:42-0500,high
10049,7311960763,https://norfolk.craigslist.org/ctd/d/chesapeak...,norfolk / hampton roads,https://norfolk.craigslist.org,31990,2017.0,ram,1500 crew cab big horn,good,8 cylinders,...,pickup,white,https://images.craigslist.org/00c0c_4rTlvLXy36...,Carvana is the safer way to buy a car During t...,NaN,va,36.670000,-76.300000,2021-04-24T13:50:49-0400,high

вообще говоря инфы для определения чем заполнять мало, да и отсутствующих значений не так много, потому лучше удалить

## статус

In [38]:
# minidf = df_nodub[df_nodub.title_status.isna()]
# minidf

uniqstat = df_nodub.title_status.unique().tolist()
uniqstat

['clean', nan, 'rebuilt', 'salvage', 'lien', 'missing', 'parts only']

In [39]:
uniqstat = [stat for stat in uniqstat if isinstance(stat, str)]
uniqstat

['clean', 'rebuilt', 'salvage', 'lien', 'missing', 'parts only']

In [40]:
sizes = [len(df_nodub[df_nodub.title_status == s]) for s in uniqstat]
sizes

[9398, 167, 91, 35, 16, 2]

In [41]:
df_nodub = df_nodub.dropna(subset=["title_status"])
df_nodub

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,type,paint_color,image_url,description,county,state,lat,long,posting_date,price_category
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020.0,ram,2500 crew cab big horn,good,NaN,...,pickup,silver,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,NaN,tn,35.060000,-85.250000,2021-04-17T12:30:50-0400,high
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016.0,ford,explorer 4wd 4dr xlt,NaN,6 cylinders,...,SUV,black,https://images.craigslist.org/00x0x_26jl9F0cnL...,***Call Us for more information at: 201-635-14...,NaN,nj,40.821805,-74.061962,2021-05-03T15:40:21-0400,medium
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017.0,volkswagen,golf r hatchback,good,NaN,...,sedan,NaN,https://images.craigslist.org/00y0y_eeZjWeiSfb...,Carvana is the safer way to buy a car During t...,NaN,ca,33.779214,-84.411811,2021-04-28T03:52:20-0700,high
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013.0,toyota,rav4,NaN,NaN,...,wagon,white,https://images.craigslist.org/00606_iGe5iXidib...,2013 Toyota RAV4 XLE 4dr SUV Offered by: R...,NaN,nc,35.715954,-78.655304,2021-04-17T10:08:57-0400,medium
4,7316474668,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800,2021.0,nissan,altima,new,4 cylinders,...,NaN,NaN,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,2021 Nissan Altima Sv with Only 8 K Miles Titl...,NaN,ny,40.654800,-73.609700,2021-05-03T18:32:06-0400,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10045,7304876387,https://chautauqua.craigslist.org/ctd/d/falcon...,chautauqua,https://chautauqua.craigslist.org,4495,2002.0,toyota,rav4,good,4 cylinders,...,SUV,white,https://images.craigslist.org/00n0n_aaEBqmzz5Z...,Transmission:Automatic Exterior Color:WHITE In...,NaN,ny,42.123900,-79.189500,2021-04-10T16:33:57-0400,low
10046,7316152972,https://binghamton.craigslist.org/ctd/d/roches...,binghamton,https://binghamton.craigslist.org,14495,2008.0,jeep,wrangler,good,6 cylinders,...,SUV,grey,https://images.craigslist.org/00000_9ZNVdXaiei...,2008 Jeep Wrangler X Offered by: R&L Auto -- ...,NaN,ny,43.216990,-77.755610,2021-05-03T09:36:30-0400,medium
10047,7310993818,https://salem.craigslist.org/ctd/d/salem-2011-...,salem,https://salem.craigslist.org,8995,2011.0,audi,a3 2.0t premium plus pzev,NaN,4 cylinders,...,wagon,black,https://images.craigslist.org/00X0X_k5JiZDDyqM...,2011 Audi A3 2.0T Premium Plus PZEV Wagon2011 ...,NaN,or,44.925908,-122.982753,2021-04-22T12:14:01-0700,low
10048,7306637427,https://madison.craigslist.org/ctd/d/madison-2...,madison,https://madison.craigslist.org,31900,2015.0,porsche,cayenne,good,6 cylinders,...,wagon,brown,https://images.craigslist.org/00O0O_gBihGEQxYT...,"2015 Porsche Cayenne AWD 4dr S E-Hybrid - $31,...",NaN,wi,43.029559,-89.397796,2021-04-14T09:14:42-0500,high
10049,7311960763,https://norfolk.craigslist.org/ctd/d/chesapeak...,norfolk / hampton roads,https://norfolk.craigslist.org,31990,2017.0,ram,1500 crew cab big horn,good,8 cylinders,...,pickup,white,https://images.craigslist.org/00c0c_4rTlvLXy36...,Carvana is the safer way to buy a car During t...,NaN,va,36.670000,-76.300000,2021-04-24T13:50:49-0400,high

аналогично недостаточно инфы

## преобразование типов в году выпуска

In [42]:
dfyear = df_nodub[["year"]]
dfyear

         year
0      2020.0
1      2016.0
2      2017.0
3      2013.0
4      2021.0
...       ...
10045  2002.0
10046  2008.0
10047  2011.0
10048  2015.0
10049  2017.0

[9709 rows x 1 columns]

In [43]:
df_nodub.year = df_nodub.year.astype(int)

df_nodub.year.info()

<class 'pandas.core.series.Series'>
Index: 9709 entries, 0 to 10049
Series name: year
Non-Null Count  Dtype
--------------  -----
9709 non-null   int32
dtypes: int32(1)
memory usage: 113.8 KB

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15996\3076540266.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nodub.year = df_nodub.year.astype(int)

In [44]:
# minidf = df_nodub.year
# minidf

In [45]:
df_nodub

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,type,paint_color,image_url,description,county,state,lat,long,posting_date,price_category
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020,ram,2500 crew cab big horn,good,NaN,...,pickup,silver,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,NaN,tn,35.060000,-85.250000,2021-04-17T12:30:50-0400,high
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016,ford,explorer 4wd 4dr xlt,NaN,6 cylinders,...,SUV,black,https://images.craigslist.org/00x0x_26jl9F0cnL...,***Call Us for more information at: 201-635-14...,NaN,nj,40.821805,-74.061962,2021-05-03T15:40:21-0400,medium
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017,volkswagen,golf r hatchback,good,NaN,...,sedan,NaN,https://images.craigslist.org/00y0y_eeZjWeiSfb...,Carvana is the safer way to buy a car During t...,NaN,ca,33.779214,-84.411811,2021-04-28T03:52:20-0700,high
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013,toyota,rav4,NaN,NaN,...,wagon,white,https://images.craigslist.org/00606_iGe5iXidib...,2013 Toyota RAV4 XLE 4dr SUV Offered by: R...,NaN,nc,35.715954,-78.655304,2021-04-17T10:08:57-0400,medium
4,7316474668,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800,2021,nissan,altima,new,4 cylinders,...,NaN,NaN,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,2021 Nissan Altima Sv with Only 8 K Miles Titl...,NaN,ny,40.654800,-73.609700,2021-05-03T18:32:06-0400,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10045,7304876387,https://chautauqua.craigslist.org/ctd/d/falcon...,chautauqua,https://chautauqua.craigslist.org,4495,2002,toyota,rav4,good,4 cylinders,...,SUV,white,https://images.craigslist.org/00n0n_aaEBqmzz5Z...,Transmission:Automatic Exterior Color:WHITE In...,NaN,ny,42.123900,-79.189500,2021-04-10T16:33:57-0400,low
10046,7316152972,https://binghamton.craigslist.org/ctd/d/roches...,binghamton,https://binghamton.craigslist.org,14495,2008,jeep,wrangler,good,6 cylinders,...,SUV,grey,https://images.craigslist.org/00000_9ZNVdXaiei...,2008 Jeep Wrangler X Offered by: R&L Auto -- ...,NaN,ny,43.216990,-77.755610,2021-05-03T09:36:30-0400,medium
10047,7310993818,https://salem.craigslist.org/ctd/d/salem-2011-...,salem,https://salem.craigslist.org,8995,2011,audi,a3 2.0t premium plus pzev,NaN,4 cylinders,...,wagon,black,https://images.craigslist.org/00X0X_k5JiZDDyqM...,2011 Audi A3 2.0T Premium Plus PZEV Wagon2011 ...,NaN,or,44.925908,-122.982753,2021-04-22T12:14:01-0700,low
10048,7306637427,https://madison.craigslist.org/ctd/d/madison-2...,madison,https://madison.craigslist.org,31900,2015,porsche,cayenne,good,6 cylinders,...,wagon,brown,https://images.craigslist.org/00O0O_gBihGEQxYT...,"2015 Porsche Cayenne AWD 4dr S E-Hybrid - $31,...",NaN,wi,43.029559,-89.397796,2021-04-14T09:14:42-0500,high
10049,7311960763,https://norfolk.craigslist.org/ctd/d/chesapeak...,norfolk / hampton roads,https://norfolk.craigslist.org,31990,2017,ram,1500 crew cab big horn,good,8 cylinders,...,pickup,white,https://images.craigslist.org/00c0c_4rTlvLXy36...,Carvana is the safer way to buy a car During t...,NaN,va,36.670000,-76.300000,2021-04-24T13:50:49-0400,high

## выбросы

In [46]:
df_nodub.year.describe()

count    9709.000000
mean     2011.053662
std         9.401666
min      1915.000000
25%      2008.000000
50%      2013.000000
75%      2017.000000
max      2022.000000
Name: year, dtype: float64

In [47]:
q25 = df_nodub.year.quantile(0.25)
q75 = df_nodub.year.quantile(0.75)
iqr = q75 - q25

boards = (q25 - 1.5 * iqr, q75 + 1.5 * iqr)

boards

(1994.5, 2030.5)

In [48]:
m = df_nodub.year[(df_nodub.year < boards[0]) | (df_nodub.year > boards[1])]
max(m.values)

1994

In [49]:
df_nodub.loc[(df_nodub.year < boards[0]), "year"] = int(boards[0])
df_nodub

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,type,paint_color,image_url,description,county,state,lat,long,posting_date,price_category
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020,ram,2500 crew cab big horn,good,NaN,...,pickup,silver,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,NaN,tn,35.060000,-85.250000,2021-04-17T12:30:50-0400,high
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016,ford,explorer 4wd 4dr xlt,NaN,6 cylinders,...,SUV,black,https://images.craigslist.org/00x0x_26jl9F0cnL...,***Call Us for more information at: 201-635-14...,NaN,nj,40.821805,-74.061962,2021-05-03T15:40:21-0400,medium
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017,volkswagen,golf r hatchback,good,NaN,...,sedan,NaN,https://images.craigslist.org/00y0y_eeZjWeiSfb...,Carvana is the safer way to buy a car During t...,NaN,ca,33.779214,-84.411811,2021-04-28T03:52:20-0700,high
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013,toyota,rav4,NaN,NaN,...,wagon,white,https://images.craigslist.org/00606_iGe5iXidib...,2013 Toyota RAV4 XLE 4dr SUV Offered by: R...,NaN,nc,35.715954,-78.655304,2021-04-17T10:08:57-0400,medium
4,7316474668,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800,2021,nissan,altima,new,4 cylinders,...,NaN,NaN,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,2021 Nissan Altima Sv with Only 8 K Miles Titl...,NaN,ny,40.654800,-73.609700,2021-05-03T18:32:06-0400,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10045,7304876387,https://chautauqua.craigslist.org/ctd/d/falcon...,chautauqua,https://chautauqua.craigslist.org,4495,2002,toyota,rav4,good,4 cylinders,...,SUV,white,https://images.craigslist.org/00n0n_aaEBqmzz5Z...,Transmission:Automatic Exterior Color:WHITE In...,NaN,ny,42.123900,-79.189500,2021-04-10T16:33:57-0400,low
10046,7316152972,https://binghamton.craigslist.org/ctd/d/roches...,binghamton,https://binghamton.craigslist.org,14495,2008,jeep,wrangler,good,6 cylinders,...,SUV,grey,https://images.craigslist.org/00000_9ZNVdXaiei...,2008 Jeep Wrangler X Offered by: R&L Auto -- ...,NaN,ny,43.216990,-77.755610,2021-05-03T09:36:30-0400,medium
10047,7310993818,https://salem.craigslist.org/ctd/d/salem-2011-...,salem,https://salem.craigslist.org,8995,2011,audi,a3 2.0t premium plus pzev,NaN,4 cylinders,...,wagon,black,https://images.craigslist.org/00X0X_k5JiZDDyqM...,2011 Audi A3 2.0T Premium Plus PZEV Wagon2011 ...,NaN,or,44.925908,-122.982753,2021-04-22T12:14:01-0700,low
10048,7306637427,https://madison.craigslist.org/ctd/d/madison-2...,madison,https://madison.craigslist.org,31900,2015,porsche,cayenne,good,6 cylinders,...,wagon,brown,https://images.craigslist.org/00O0O_gBihGEQxYT...,"2015 Porsche Cayenne AWD 4dr S E-Hybrid - $31,...",NaN,wi,43.029559,-89.397796,2021-04-14T09:14:42-0500,high
10049,7311960763,https://norfolk.craigslist.org/ctd/d/chesapeak...,norfolk / hampton roads,https://norfolk.craigslist.org,31990,2017,ram,1500 crew cab big horn,good,8 cylinders,...,pickup,white,https://images.craigslist.org/00c0c_4rTlvLXy36...,Carvana is the safer way to buy a car During t...,NaN,va,36.670000,-76.300000,2021-04-24T13:50:49-0400,high

In [50]:
df_nodub = df_nodub.drop(["type", "paint_color", "drive", "condition", "VIN", "cylinders", "size", "county"], axis=1)
df_nodub.to_csv("some_prepar.csv", index=False)